### ISSUE TITLE
mix ecto.setup && mix ecto.migrate

### ISSUE THREAD

**Issue by denegny** [elixir-lang-moscow/site#41]
mix ecto.setup && mix ecto.migrate

```
== Compilation error in file lib/elixir_lang_moscow/endpoint.ex ==
** (CompileError) lib/elixir_lang_moscow/endpoint.ex:1: inlined function current_time/0 undefined
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by sobolevn** [comment]
@denegny thanks for reporting! I have not touched this for a while.

So, I guess it is full of bugs. I am planning to rewrite it completely soon. 
Do you want to help?

**Comment by denegny** [comment]
ок)

**Comment by fenwer** [comment]
Same problem with mix compile
Erlang 20.2.4
Elixir 1.6.1 (compiled with OTP 20)
